#-------------------------------------------------#
#           GENERAL                               #
#-------------------------------------------------#
version: 2.9.0.{build}-alpha
configuration: Release

branches:
 only:
  - master
  - develop
  
#-------------------------------------------------#
#           ENVIRONMENT                           #
#-------------------------------------------------#
os: Visual Studio 2015
 
#-------------------------------------------------#
#           INIT                                  #
#-------------------------------------------------#

init:
 - cmd: echo Starting CI Task
 - git config --global core.autocrlf true
 
#-------------------------------------------------#
#           INSTALL                               #
#-------------------------------------------------#
install:
    - ps: Invoke-WebRequest https://api.nuget.org/downloads/nuget.exe -OutFile nuget.exe

#-------------------------------------------------#
#           BUILD CONFIGURATION                   #
#-------------------------------------------------#

# patch project.json files and install DNVM
before_build:
 - cmd: echo NuGet Restore
 - cmd: nuget.exe restore src
 - cmd: echo NuGet Insatt XUnit
 - cmd: nuget.exe install xunit.runner.console -ExcludeVersion -Pre -OutputDirectory packages
 - cmd: nuget.exe install xunit.runner.msbuild -ExcludeVersion -Pre -OutputDirectory packages

build_script:
 - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
 - cmd: msbuild src\QuickIO.sln /m:4 /nologo /v:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
 - cmd: RunAllTests
 
test: off
#-------------------------------------------------#
#           DEPLOY CONFIGURATION                  #
#-------------------------------------------------#

