#-------------------------------------------------#
#           GENERAL                               #
#-------------------------------------------------#
version: 2.9.0-alpha
configuration: Release

branches:
 only:
  - master
  - develop
  
#-------------------------------------------------#
#           ENVIRONMENT                           #
#-------------------------------------------------#
os: Visual Studio 2015
 
#-------------------------------------------------#
#           INIT                                  #
#-------------------------------------------------#

init:
 - cmd: echo Starting CI Task
 - git config --global core.autocrlf true
 
#-------------------------------------------------#
#           INSTALL                               #
#-------------------------------------------------#

#-------------------------------------------------#
#           BUILD CONFIGURATION                   #
#-------------------------------------------------#

# patch project.json files and install DNVM
before_build:
 - cmd: echo NuGet Restore
 - cmd: nuget.exe restore src

build_script:
 - cmd: echo Build Script
#-------------------------------------------------#
#           DEPLOY CONFIGURATION                  #
#-------------------------------------------------#

