name: NET

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

env:
  BuildConfig: Release
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
    build-win:
      runs-on: windows-latest
      steps:
      
      - name: Cancel previous builds in PR
        uses: styfle/cancel-workflow-action@0.12.1
          
      - name: 'Checkout Code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: Setup .NET SDK 7.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Setup .NET SDK 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Setup .NET SDK 9.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Versioning
        uses: dotnet/nbgv@master
        id: nbgv

      - name: Version Info
        run: |
          echo 'SemVer2: ${{ steps.nbgv.outputs.SemVer2 }}'

      - name: Build with dotnet
        run: dotnet build
              --configuration ${{ env.BuildConfig }}
              /p:Version=${{ steps.nbgv.outputs.AssemblyVersion }}

      - name: Test with dotnet
        run: dotnet test

      - name: Pack NuGet
        run: dotnet pack
              --configuration ${{ env.BuildConfig }}
              /p:ContinuousIntegrationBuild=true
              /p:Version=${{ steps.nbgv.outputs.NuGetPackageVersion }}

      - name: Push to NuGet
        run: dotnet nuget push **/*.nupkg
                --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
                --source https://api.nuget.org/v3/index.json
                --no-symbols
                --skip-duplicate

      # - name: Update CHANGELOG
      #   id: changelog
      #   uses: requarks/changelog-action@v1
      #   with:
      #     token: ${{ github.token }}
      #     tag: ${{ github.ref_name }}

      # - name: Create Release
      #   uses: ncipollo/release-action@v1.12.0
      #   with:
      #     allowUpdates: true
      #     draft: false
      #     makeLatest: true
      #     name: ${{ github.ref_name }}
      #     body: ${{ steps.changelog.outputs.changes }}
      #     token: ${{ github.token }}